PARALLEL_WORKERS_COUNT = 3
DEFAULT_BROWSER = "firefox"
LOG_FILE_NAME = 'test.log'
WEBSITE_URL = 'https://demo.applitools.com/'
EXPECTED_COMPLETED_TRANSACTIONS = 3
EXPECTED_TOTAL_BALANCE_VALUE = "$350"